/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "comparison": {
    "base": "comparison",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1920,
    "height": 1221,
    "fallbackWidth": 1920,
    "fallbackHeight": 1221,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "harbour": {
    "base": "harbour",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 1920,
    "height": 1440,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "highlights": {
    "base": "highlights",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 1920,
    "fallbackHeight": 1280,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "istria": {
    "base": "istria",
    "width": 1280,
    "height": 960,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "koper": {
    "base": "koper",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "lake-bled": {
    "base": "lake-bled",
    "width": 1920,
    "height": 1440,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 1920,
    "height": 1221,
    "fallbackWidth": 1920,
    "fallbackHeight": 1221,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "old-town": {
    "base": "old-town",
    "width": 1920,
    "height": 1341,
    "fallbackWidth": 1920,
    "fallbackHeight": 1341,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "piran": {
    "base": "piran",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "planner": {
    "base": "planner",
    "width": 1920,
    "height": 1221,
    "fallbackWidth": 800,
    "fallbackHeight": 509,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "port-day": {
    "base": "port-day",
    "width": 1920,
    "height": 1440,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "postojna": {
    "base": "postojna",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "predjama": {
    "base": "predjama",
    "width": 1920,
    "height": 2888,
    "fallbackWidth": 800,
    "fallbackHeight": 1203,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "relaxed": {
    "base": "relaxed",
    "width": 1920,
    "height": 1221,
    "fallbackWidth": 800,
    "fallbackHeight": 509,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
